local th = require("config.theme")
local sn = require("plugins.snacks")
local fzf = require("plugins.fzf")

require("config.options")

require("plugins.conform")
require("plugins.lspconfig")
vim.cmd("packadd nvim-lspconfig")
require("plugins.wichkey")
require("plugins.treesitter")
require("plugins.lazydev")
require("plugins.completion")
fzf.setup()
require("plugins.ai")
require("plugins.colorizer")
require("plugins.easy-align")
require("plugins.file-explorer")
require("plugins.flash")
require("plugins.git")
require("plugins.keep-aspect-ratio")
require("plugins.lualine")
require("plugins.mini-pairs")
require("plugins.mini-splitjoin")
require("plugins.mini-surround")
require("plugins.search-and-replace")
sn.setup()
require("plugins.tmux-navigator")
require("plugins.ts-autotag")
require("plugins.undotree")
require("plugins.visual-star-search")

require("config.autocmds")
th.setup()
th.load_theme()

require("config.mappings")

vim.defer_fn(function()
  --defer non-essential configs,
  --purely for experimental purposes:
  require("plugins.incline")
  require("plugins.todo-comments")
  require("plugins.render-markdown")
end, 100)
