local ensure_installed = {
    "astro",
    "bash",
    "css",
    "dockerfile",
    "fish",
    "git_rebase",
    "gitcommit",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "html",
    "http",
    "hurl",
    "javascript",
    "json",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "nu",
    "python",
    "sql",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "typst",
    "vimdoc",
    "yaml",
    "kdl",
}

return {
    {
        "nvim-treesitter/nvim-treesitter",
        dependencies = {
            "nvim-treesitter/nvim-treesitter-textobjects",
            "andymass/vim-matchup",
        },
        build = ":TSUpdate",
        event = "VeryLazy",
        main = "nvim-treesitter.configs",
        opts = {
            ensure_installed = ensure_installed,
            auto_install = true,
            highlight = { enable = true },
            indent = { enable = true },
            matchup = { enable = true },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<C-space>",
                    node_incremental = "<C-space>",
                    scope_incremental = "<C‑s>",
                    node_decremental = "<BS>",
                },
            },
            textobjects = {
                select = {
                    enable = true,
                    lookahead = true,
                    keymaps = {
                        ["af"] = "@function.outer",
                        ["if"] = "@function.inner",
                        ["ac"] = "@conditional.outer",
                        ["ic"] = "@conditional.inner",
                        ["al"] = "@loop.outer",
                        ["il"] = "@loop.inner",
                    },
                },
            },
        },
    },
}
